I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 27, in script
    e "You've created a new Ren'Py game."
Exception: Sayer 'e' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 27, in script
    e "You've created a new Ren'Py game."
  File "C:\Users\proatec\Downloads\renpy-8.1.2-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\proatec\Downloads\renpy-8.1.2-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'e' is not defined.

Windows-10-10.0.19041 AMD64
Ren'Py 8.1.2.23090503
game 1.0
Thu Sep 14 15:35:31 2023
